In [1]:
import torch

inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your      (x^1)
    [0.55, 0.87, 0.66], # journey   (x^2)
    [0.57, 0.85, 0.64], # starts    (x^3)
    [0.22, 0.58, 0.33], # with      (x^4)
    [0.77, 0.25, 0.10], # one       (x^5)
    [0.05, 0.89, 0.55], # step      (x^6)
])

In [2]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])
# print(inputs.shape) # torch.Size([6, 3])
# print(attn_scores_2) # tensor([9.6668e+21, 1.1771e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)

print(attn_scores_2) # tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.1648])

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.1648])


In [3]:
res = 0
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]

print(res)
print(torch.dot(inputs[0], query))

tensor(0.9544)
tensor(0.9544)


In [4]:
print(attn_scores_2) # tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.1648])

attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
print(f"어텐션 가중치: {attn_weights_2_tmp}")
print(f"합: {attn_weights_2_tmp.sum()}")

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.1648])
어텐션 가중치: tensor([0.1437, 0.2252, 0.2222, 0.1270, 0.1065, 0.1754])
합: 1.0


In [5]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores_2)
print(f"어텐션 가중치: {attn_weights_2_naive}")
print(f"합: {attn_weights_2_naive.sum()}")

어텐션 가중치: tensor([0.1368, 0.2349, 0.2303, 0.1224, 0.1068, 0.1688])
합: 0.9999999403953552


In [6]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print(f"어텐션 가중치: {attn_weights_2}")
print(f"합: {attn_weights_2.sum()}")

어텐션 가중치: tensor([0.1368, 0.2349, 0.2303, 0.1224, 0.1068, 0.1688])
합: 1.0


In [7]:
print(query) # inputs[1]

context_vec_2 = torch.zeros(query.shape)
print(context_vec_2, context_vec_2.shape)

for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i

print(context_vec_2)

tensor([0.5500, 0.8700, 0.6600])
tensor([0., 0., 0.]) torch.Size([3])
tensor([0.4369, 0.6686, 0.5681])


In [8]:
# 모든 문맥 벡터를 계산

attn_scores = torch.empty(6, 6)

# print(inputs)
for i , x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)

print(f"attention scores:\n{attn_scores}")

attention scores:
tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6445],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.1648],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.1370],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.7087],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.3160],
        [0.6445, 1.1648, 1.1370, 0.7087, 0.3160, 1.0971]])


In [14]:
# 행렬 곱셈을 사용

print(f"inputs:\n{inputs}\n")
# inputs = torch.tensor([
#     [0.43, 0.15, 0.89], # Your      (x^1)
#     [0.55, 0.87, 0.66], # journey   (x^2)
#     [0.57, 0.85, 0.64], # starts    (x^3)
#     [0.22, 0.58, 0.33], # with      (x^4)
#     [0.77, 0.25, 0.10], # one       (x^5)
#     [0.05, 0.89, 0.55], # step      (x^6)
# ])

attn_scores = inputs @ inputs.T
print(f"attn_scores:\n{attn_scores}\n")

attn_weights = torch.softmax(attn_scores, dim=-1)
print(f"attn_weights:\n{attn_weights}")

inputs:
tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8900, 0.5500]])

attn_scores:
tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6445],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.1648],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.1370],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.7087],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.3160],
        [0.6445, 1.1648, 1.1370, 0.7087, 0.3160, 1.0971]])

attn_weights:
tensor([[0.2094, 0.2002, 0.1978, 0.1240, 0.1218, 0.1468],
        [0.1368, 0.2349, 0.2303, 0.1224, 0.1068, 0.1688],
        [0.1373, 0.2340, 0.2297, 0.1227, 0.1094, 0.1668],
        [0.1422, 0.2055, 0.2027, 0.1449, 0.1251, 0.1796],
        [0.1522, 0.1953, 0.1969, 0.1363, 0.1873, 0.1321],
        [0.1302, 0.2191, 0.2131, 0.1389, 0.0938, 0.2048]])


In [16]:
print(f"모든 행의 합: {attn_weights.sum(dim=1)}")

모든 행의 합: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [18]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)
print(context_vec_2)

tensor([[0.4413, 0.6067, 0.5789],
        [0.4369, 0.6686, 0.5681],
        [0.4383, 0.6665, 0.5669],
        [0.4269, 0.6475, 0.5510],
        [0.4659, 0.6035, 0.5267],
        [0.4110, 0.6776, 0.5648]])
tensor([0.4369, 0.6686, 0.5681])
